FACTION_NAME:
  MAX_CHARACTERS: 16
  MIN_CHARACTERS: 3
  BLOCKED_NAMES:
    - "hcteams" # ;)
FACTION_DTR:
  STARTING_DTR: 1.1
  DTR_PER_PLAYER: 0.5
FACTION_ALLIES:
  ENABLED: TRUE
  DAMAGE_ALLIES: FALSE
  MAX_ALLIES: 1