FACTION_GENERAL:
  STARTING_DTR: 1.1
  DTR_PER_PLAYER: 0.5
  REGEN_DELAY: 90 #every 90 seconds regen 0.1 dtr
  ALLIES:
    ENABLED: TRUE
    DAMAGE_ALLIES: FALSE
    MAX_ALLIES: 1
  MAX_PLAYERS: 30
FACTION_NAME:
  MAX_CHARACTERS: 16
  MIN_CHARACTERS: 3
  BLOCKED_NAMES:
    - "hcteams" # ;)
TAB_LIST:
  ENABLED: TRUE
  FRIENDLY_COLOR: "DARK_GREEN"
  ALLY_COLOR: "LIGHT_PURPLE"
  ENEMY_COLOR: "YELLOW"
FACTION_CLAIMING:
  WAND:
    TYPE: "GOLD_HOE"
    DATA: 0
    NAME: "&aClaiming Wand"
    LORE:
      - "&aLeft click the ground&7 to set the &afirst&7 point."
      - "&aRight click the ground&7 to set the &asecond&7 point."
      - "&aSneak and left click the air&7 to claim once both points set."
      - "&aRight click the air twice&7 to clear your selection."

FACTION_CHAT:
  ENABLED: TRUE
  NO_FACTION: ""
  FRIENDLY: "&6[&2%TAG%&6]&r"
  ALLY: "&6[&d%TAG%&6]&r"
  ENEMY: "&6[&e%TAG%&6]&r"